// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aowypxtljzpvvitrjepv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvd3lweHRsanpwdnZpdHJqZXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjg0NDEsImV4cCI6MjA3MTkwNDQ0MX0.D59xInWPzc1HyXq7e2-mraC-7_7Iw9BliHE6EXTT3Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});